apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: vets-service
  name: vets-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vets-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o petclinic_chart/templates
        kompose.image-pull-secret: regcred
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-default: "true"
        io.kompose.service: vets-service
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_VETS_SERVICE }}'
          name: vets-service
          ports:
            - containerPort: 8083
              hostPort: 8083
              protocol: TCP
          resources: {}
      initContainers:
              - name: init-config-server
                image: busybox
                command: ['sh', '-c', 'until nc -z config-server:8888; do echo waiting for config-server; sleep 2; done;']
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}
